#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
SERVICE_FILE="$PROJECT_DIR/ondepi.service"
WRAPPER="$PROJECT_DIR/ondepi"
BIN_LINK="/usr/local/bin/ondepi"
SYSTEMD_LINK="/etc/systemd/system/ondepi.service"
CURRENT_USER="$(whoami)"
CURRENT_GROUP="$(id -gn)"

# --- System dependencies ---
echo "Installing system dependencies..."
sudo apt update
sudo apt install -y libportaudio2 ffmpeg

# --- uv ---
if ! command -v uv >/dev/null 2>&1; then
  echo "uv not found. Installing..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi
export PATH="$HOME/.local/bin:$PATH"

# --- Python venv & package ---
echo "Setting up virtual environment..."
uv venv "$PROJECT_DIR/.venv"
uv pip install -e "$PROJECT_DIR[dev]"

# --- Wrapper script ---
chmod +x "$WRAPPER"

# --- Generate service file ---
echo "Generating ondepi.service..."
cat > "$SERVICE_FILE" <<EOF
# Generated by install.sh — do not edit manually.
# Re-run install.sh to regenerate with correct paths.

[Unit]
Description=OndePi - Headless audio live source streamer for AzuraCast
After=network-online.target sound.target
Wants=network-online.target

[Service]
Type=simple
User=$CURRENT_USER
Group=$CURRENT_GROUP
SupplementaryGroups=dialout audio
ExecStart=$BIN_LINK
WorkingDirectory=$PROJECT_DIR

Restart=always
RestartSec=10

Nice=-5
LimitNOFILE=65536
# Let PortAudio put the ALSA capture callback on a realtime scheduler so it
# isn't starved by the concurrent webradio decoder + stream encoder (xruns).
LimitRTPRIO=95
LimitMEMLOCK=infinity

StandardOutput=journal
StandardError=journal
SyslogIdentifier=ondepi

[Install]
WantedBy=multi-user.target
EOF

# --- Symlinks ---
echo "Creating symlink $BIN_LINK -> $WRAPPER"
sudo ln -sf "$WRAPPER" "$BIN_LINK"

echo "Creating symlink $SYSTEMD_LINK -> $SERVICE_FILE"
sudo ln -sf "$SERVICE_FILE" "$SYSTEMD_LINK"

# --- Systemd ---
echo "Reloading systemd daemon..."
sudo systemctl daemon-reload

echo ""
echo "Install complete!"
echo ""
echo "  Auto-start on boot: sudo systemctl enable ondepi"
echo "  Start:   sudo systemctl start ondepi"
echo "  Stop:    sudo systemctl stop ondepi"
echo "  Status:  sudo systemctl status ondepi"
echo "  Logs:    journalctl -u ondepi -f"
echo ""
